breaking-change:
  - changed-files:
      - any-glob-to-any-file:
        - "changes/*.breaking.rst"

feature:
  - changed-files:
      - any-glob-to-any-file:
        - "changes/*.feature.rst"

fix:
  - changed-files:
      - any-glob-to-any-file:
        - "changes/*.fix.rst"

documentation:
  - changed-files:
      - all-globs-to-any-file:
          - "*.rst"
          - "!CHANGES.rst"
          - "!changes/*"
      - any-glob-to-any-file:
          - "docs/**/*"
          - "*.md"
          - ".readthedocs.yaml"
          - "LICENSE"
          - "changes/*.docs.rst"

packaging:
  - changed-files:
      - any-glob-to-any-file:
          - "pyproject.toml"

# --------------------------------------- testing ---------------------------------------

automation:
  - changed-files:
      - any-glob-to-any-file:
        - ".github/**"

testing:
  - changed-files:
      - any-glob-to-any-file:
        - "**/tests/**"
        - "**/regtest/**"
        - ".github/workflows/test*.yml"
        - "**/conftest.py"
