exclude: ".*\\.asdf$"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      # - id: end-of-file-fixer
      # - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.9.2'
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
      - id: numpydoc-validation
        exclude: |
          (?x)^(
          docs/.* |
          tests/.* |
          .*/tests/.* |
          .*/_tests/.* |
          src/__init__.py |
          )$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.0
    hooks:
    - id: codespell
      args: ["--write-changes"]
