# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/refs/heads/main/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - htmlzip
  - pdf

build:
  os: ubuntu-lts-latest
  tools:
    python: latest
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - towncrier build --keep

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
