version: 2

sphinx:
  configuration: docs/source/conf.py

formats:
  - htmlzip
  - pdf

build:
  os: "ubuntu-22.04"
  tools:
    python: mambaforge-4.10

conda:
  environment: docs/rtd_environment.yaml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
