[tox]
envlist =
    py3{,11,12,13,14}{,-jwst}{,-devdeps}{,-cov}{,-nocrds}{,-xdist}

[testenv]
allowlist_externals =
    jwst: bash
    jwst: git
description =
    run tests
    xdist: using parallel processing
    oldestdeps: with the oldest supported version of key dependencies
    cov: with coverage
pass_env =
    TOXENV
    CI
    CODECOV_*
    HOME
    CRDS_*
set_env =
    cov: COVERAGE_RC_FILE=pyproject.toml
    cov: COVERAGE_FILE={toxinidir}/.coverage
extras =
    test
deps =
    xdist: pytest-xdist
    cov: pytest-cov
    oldestdeps: minimum_dependencies
package=
    cov: editable
    !cov: wheel
change_dir =
    jwst: {env_tmp_dir}
commands_pre =
    oldestdeps: minimum_dependencies stdatamodels --filename {env_tmp_dir}/requirements-min.txt
    oldestdeps: pip install -r {env_tmp_dir}/requirements-min.txt
    jwst: bash -c "pip freeze -q | grep 'stdatamodels @' > {env_tmp_dir}/requirements.txt"
    jwst: git clone https://github.com/spacetelescope/jwst.git
    jwst: pip install -e jwst[test]
    devdeps: pip install -r {toxinidir}/requirements-dev.txt -U --upgrade-strategy eager
    jwst: pip install -r {env_tmp_dir}/requirements.txt
    pip freeze
commands =
    pytest \
    xdist: -n auto \
    cov: --cov=src --cov-report=term-missing --cov-report=xml \
    jwst: jwst \
    nocrds: --no-crds
    {posargs}
