name: tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  supported-pythons:
    runs-on: ubuntu-latest
    steps:
      - id: supported-pythons
        uses: zacharyburnett/supported-pythons@9186be100e84431de457f333fe8f793f079f5b66 # 2.0.3
        with:
          package: ${{ github.repository }}
          package-ref: ${{ github.ref || github.sha }}
    outputs:
      versions: ${{ steps.supported-pythons.outputs.versions }}
  test:
    needs:
      - supported-pythons
    strategy:
      fail-fast: false
      matrix:
        runs-on: ["ubuntu-latest"]
        python-version: ${{ fromJSON(needs.supported-pythons.outputs.versions) }}
        coverage: [false]
        include:
          - name: run tests with coverage (latest Python, ubuntu-latest)
            runs-on: "ubuntu-latest"
            python-version: "${{ needs.supported-pythons.outputs.latest }}"
            coverage: true
          - name: run tests (latest Python, macos-latest)
            runs-on: "macos-latest"
            python-version: "${{ needs.supported-pythons.outputs.latest }}"
    name: ${{ matrix.name || format('run tests (Python {0}, {1})',matrix.python-version, matrix.runs-on) }})
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install ".[test]" ${{ matrix.coverage && 'coverage pytest-cov' || '' }}
      - run: pytest ${{ matrix.coverage && '--cov' || '' }}
      - if: matrix.coverage
        name: report coverage to summary
        run: |
          coverage combine
          echo '## Coverage Report' >> $GITHUB_STEP_SUMMARY
          coverage report -i -m --format=markdown | tee -a $GITHUB_STEP_SUMMARY
